# permissions for end users to view tves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfe-viewer-role
rules:
- apiGroups:
  - cache.thetacloud.com
  resources:
  - tves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.thetacloud.com
  resources:
  - tves/status
  verbs:
  - get
